namespace PlayerRomance.Net;

public enum MessageType
{
    RequestSnapshot = 0,
    Snapshot = 1,
    ProposalDating = 2,
    DatingDecision = 3,
    StartDateEvent = 4,
    DateEventStep = 5,
    ProposalMarriage = 6,
    MarriageDecision = 7,
    PregnancyOptIn = 8,
    TryForBabyRequest = 9,
    TryForBabyDecision = 10,
    ChildBorn = 11,
    ChildGrewUp = 12,
    FarmWorkReport = 13,
    CarryRequest = 14,
    CarryDecision = 15,
    CarryState = 16,
    CarryStop = 17,
    ImmersiveDateRequest = 18,
    ImmersiveDateDecision = 19,
    ImmersiveDateState = 20,
    ImmersiveDateInteractionRequest = 21,
    ImmersiveDateInteractionResult = 22,
    HeartDelta = 23,
    HoldingHandsRequest = 24,
    HoldingHandsDecision = 25,
    HoldingHandsState = 26,
    HoldingHandsStop = 27,
    Error = 28,
    ChildCommand = 29,
    ChildCommandResult = 30,
    DateEventPhase = 31,
    EndDateEvent = 32,
    NpcSync = 33
}
